# Dependabot - Automated dependency updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
