# Gradle
org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official

# Quarkus platform coordinates (used by Quarkus Gradle plugin)
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.17.8
platform.quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
