quarkus.application.name=fbs-demo-mock-services
quarkus.http.port=8095

# CORS (frontend dev server)
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,API-Version

# Kafka
%dev.kafka.bootstrap.servers=localhost:29092
mp.messaging.incoming.bericht-ontvangen.topic=nl.fbs.bericht-ontvangen
mp.messaging.incoming.bericht-ontvangen.group.id=fbs-demo-mock-services
mp.messaging.incoming.bericht-ontvangen.auto.offset.reset=latest
mp.messaging.incoming.bericht-ontvangen.failure-strategy=ignore
mp.messaging.incoming.bericht-ontvangen.value.deserializer=io.cloudevents.kafka.CloudEventDeserializer
mp.messaging.incoming.bericht-ontvangen.connector=smallrye-kafka
