# Berichtenlijst - Application Configuration
# =============================================

# Application
quarkus.application.name=berichtenlijst

# HTTP
quarkus.http.port=8081

# Datasource
quarkus.datasource.db-kind=postgresql
# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/berichtenlijst
# quarkus.datasource.username=
# quarkus.datasource.password=

# OpenAPI
quarkus.smallrye-openapi.info-title=Berichtenlijst API
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.info-description=Federatief Berichtenstelsel - Berichtenlijst Service

# OIDC
# quarkus.oidc.auth-server-url=
# quarkus.oidc.client-id=

# Cache
quarkus.cache.enabled=true
