# Notificatie - Application Configuration
# =========================================

# Application
quarkus.application.name=notificatie

# HTTP
quarkus.http.port=8082

# Kafka
# kafka.bootstrap.servers=localhost:29092

# Mailer
# quarkus.mailer.from=noreply@fbs.nl
# quarkus.mailer.host=localhost
# quarkus.mailer.port=1025

# OpenAPI
quarkus.smallrye-openapi.info-title=Notificatie API
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.info-description=Federatief Berichtenstelsel - Notificatie Service
